// Catalogue from the user supplied progression specification.
export const PROGRESSION_ACHIEVEMENTS = [
  {
    id: 'p1-01',
    title: 'La teoría es lo primero',
    description: 'Completa el tutorial del juego.',
    tier: 0,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'tutorial',
    target: 1,
  },
  {
    id: 'p1-02',
    title: 'Licenciado en Hexfortia',
    description: 'Lee «El dilema de Hexfortia».',
    tier: 0,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'story',
    target: 1,
  },
  {
    id: 'p1-03',
    title: 'Que empiece el juego',
    description: 'Completa tu primera partida.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'matches',
    target: 1,
  },
  {
    id: 'p1-04',
    title: 'Solo puede quedar uno',
    description: 'Gana tu primera partida local.',
    tier: 0,
    hidden: false,
    modes: ['local'],
    minDifficulty: 0,
    metric: 'wins',
    target: 1,
  },
  {
    id: 'p1-05',
    title: '¡Chúpate esa!',
    description: 'Gana tu primera partida en línea.',
    tier: 0,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'wins',
    target: 1,
  },
  {
    id: 'p1-06',
    title: 'Hoy mando yo',
    description: 'Gana tu primera partida contra Hexfortia.',
    tier: 0,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 0,
    metric: 'wins',
    target: 1,
  },
  {
    id: 'p1-07',
    title: 'Cambio de rumbo',
    description: 'Cambia la orientación de un soldado sin desplazarte.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'rotate',
    target: 1,
  },
  {
    id: 'p1-08',
    title: 'Donde pongo el cañón pongo la bala',
    description: 'Cambia la orientación del cañón de un tanque sin desplazarte.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'orient',
    target: 1,
  },
  {
    id: 'p1-09',
    title: '¡Aparta!',
    description: 'Realiza un desplazamiento de al menos cinco casillas con un embestidor.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'ramDistance',
    target: 5,
  },
  {
    id: 'p1-10',
    title: '¿Y ahora qué disparo?',
    description: 'Quédate sin misiles con un lanzamisiles.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'emptyMissiles',
    target: 1,
  },
  {
    id: 'p1-11',
    title: 'Por encima de todo',
    description: 'Sobrevuela una unidad aliada con un dron.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'flyAlly',
    target: 1,
  },
  {
    id: 'p1-12',
    title: 'Con vistas al enemigo',
    description: 'Quédate sobre una unidad enemiga con un avión.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'aboveEnemy',
    target: 1,
  },
  {
    id: 'p1-13',
    title: '¡Transformación!',
    description: 'Abandona un vehículo para convertirlo en soldado.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'transform',
    target: 1,
  },
  {
    id: 'p1-14',
    title: 'Calentando motores',
    description: 'Juega 5 partidas.',
    tier: 0,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'matches',
    target: 5,
  },
  {
    id: 'p1-15',
    title: 'No hay dos sin tres',
    description: 'Consigue una racha de actividad de 3 días.',
    tier: 0,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'activity',
    target: 3,
  },
  {
    id: 'p1-16',
    title: 'A quemarropa',
    description: 'Destruye una unidad enemiga mediante un ataque cuerpo a cuerpo.',
    tier: 0,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'meleeKills',
    target: 1,
  },
  {
    id: 'p1-17',
    title: 'La distancia hace el olvido',
    description: 'Destruye una unidad enemiga con un ataque a distancia.',
    tier: 0,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'rangedKills',
    target: 1,
  },
  {
    id: 'p1-18',
    title: 'Y de paso, otro',
    description: 'Destruye dos unidades enemigas con la misma unidad en una partida.',
    tier: 0,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'unitKills',
    target: 2,
  },
  {
    id: 'p1-19',
    title: '¿Había dos?',
    description: 'Realiza un ataque sobre una casilla con dos unidades enemigas apiladas.',
    tier: 0,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'stackAttack',
    target: 1,
  },
  {
    id: 'p1-20',
    title: 'A cubierto',
    description: 'Termina una partida sin que tu escudo antiaéreo haya sido destruido.',
    tier: 0,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'shieldSurvived',
    target: 1,
  },
  {
    id: 'p2-01',
    title: 'No he venido a participar',
    description: 'Alcanza los 1200 puntos de clasificación.',
    tier: 1,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'onlineRating',
    target: 1200,
  },
  {
    id: 'p2-02',
    title: 'No hay quien me pare',
    description: 'Gana 5 partidas en línea.',
    tier: 1,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'wins',
    target: 5,
  },
  {
    id: 'p2-03',
    title: '¿Seguro que eres inteligente?',
    description: 'Gana 3 partidas contra Hexfortia.',
    tier: 1,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 1,
    metric: 'wins',
    target: 3,
  },
  {
    id: 'p2-04',
    title: 'Hoy no se vuela',
    description: 'Destruye dos unidades aéreas enemigas en una partida.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'airKillsMatch',
    target: 2,
  },
  {
    id: 'p2-05',
    title: 'Triple asalto',
    description: 'Destruye tres unidades enemigas con soldados en una misma partida.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'soldierKills',
    target: 3,
  },
  {
    id: 'p2-06',
    title: 'A sus órdenes',
    description: 'Utiliza al menos una vez cada tipo de unidad en tres partidas diferentes.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'allTypesUsed',
    target: 3,
  },
  {
    id: 'p2-07',
    title: 'Aquí ha pasado algo',
    description: 'Destruye al menos el 50% de las unidades enemigas en una partida en línea.',
    tier: 1,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'halfEnemies',
    target: 1,
  },
  {
    id: 'p2-08',
    title: 'Ahora somos familia',
    description: 'Captura una unidad enemiga con el capturador.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'conversions',
    target: 1,
  },
  {
    id: 'p2-09',
    title: '¿Te creías indestructible?',
    description: 'Destruye una fortaleza con tres puntos de vida.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'fortressThree',
    target: 1,
  },
  {
    id: 'p2-10',
    title: 'Servicio de limpieza',
    description: 'Elimina 100 unidades rivales.',
    tier: 1,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 1,
    metric: 'kills',
    target: 100,
  },
  {
    id: 'p2-11',
    title: 'No era para tanto',
    description:
      'Gana una partida contra un jugador con al menos 150 puntos de clasificación más que tú.',
    tier: 1,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'ratingGap',
    target: 150,
  },
  {
    id: 'p2-12',
    title: 'Tenemos toda la tarde',
    description: 'Juega 10 partidas locales de al menos 50 turnos.',
    tier: 1,
    hidden: false,
    modes: ['local'],
    minDifficulty: 0,
    metric: 'longMatches',
    target: 10,
  },
  {
    id: 'p2-13',
    title: 'Una más y lo dejo',
    description: 'Juega 10 partidas en línea.',
    tier: 1,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'matches',
    target: 10,
  },
  {
    id: 'p2-14',
    title: 'Empezamos a conocernos',
    description: 'Juega 5 partidas contra Hexfortia.',
    tier: 1,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 1,
    metric: 'matches',
    target: 5,
  },
  {
    id: 'p2-15',
    title: 'Ya es costumbre',
    description: 'Consigue una racha de actividad de 10 días.',
    tier: 1,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'activity',
    target: 10,
  },
  {
    id: 'p2-16',
    title: '¿Ya se ha terminado?',
    description: 'Gana 3 partidas en línea con límite de tiempo.',
    tier: 1,
    hidden: true,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'timedWins',
    target: 3,
  },
  {
    id: 'p2-17',
    title: 'Cazatanques',
    description: 'Destruye tres tanques enemigos en una misma partida.',
    tier: 1,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'tankKills',
    target: 3,
  },
  {
    id: 'p2-18',
    title: 'Embestidor embestido',
    description: 'Ataca a un embestidor enemigo con un embestidor.',
    tier: 1,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'ramEnemy',
    target: 1,
  },
  {
    id: 'p2-19',
    title: 'Señor de los cielos',
    description: 'Destruye 15 unidades aéreas con unidades aéreas.',
    tier: 1,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'airByAirKills',
    target: 15,
  },
  {
    id: 'p2-20',
    title: 'No pienso aterrizar',
    description: 'Utiliza el ataque kamikaze 5 veces.',
    tier: 1,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 1,
    metric: 'kamikaze',
    target: 5,
  },
  {
    id: 'p3-01',
    title: 'Ya son palabras mayores',
    description: 'Alcanza 1500 puntos de clasificación.',
    tier: 2,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'onlineRating',
    target: 1500,
  },
  {
    id: 'p3-02',
    title: 'Suma y sigue',
    description: 'Gana 15 partidas locales de al menos 50 turnos.',
    tier: 2,
    hidden: false,
    modes: ['local'],
    minDifficulty: 0,
    metric: 'longWins',
    target: 15,
  },
  {
    id: 'p3-03',
    title: 'Captcha superado',
    description: 'Gana 10 partidas contra Hexfortia.',
    tier: 2,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 2,
    metric: 'wins',
    target: 10,
  },
  {
    id: 'p3-04',
    title: 'Se me da fatal perder',
    description: 'Gana 5 partidas en línea consecutivas.',
    tier: 2,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'winStreak',
    target: 5,
  },
  {
    id: 'p3-05',
    title: 'Me da tiempo antes del café',
    description:
      'Gana 10 partidas en línea con el tiempo total configurado a 5 minutos por jugador.',
    tier: 2,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'blitzWins',
    target: 10,
  },
  {
    id: 'p3-06',
    title: '¿Queda alguien ahí?',
    description: 'Gana 10 partidas destruyendo todas las unidades enemigas.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'cleanWins',
    target: 10,
  },
  {
    id: 'p3-07',
    title: 'Otro para mi colección',
    description: 'Captura dos unidades enemigas con un capturador.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'conversionsMatch',
    target: 2,
  },
  {
    id: 'p3-08',
    title: '¿Eso era todo?',
    description: 'Gana 3 partidas después de que tu fortaleza haya perdido 1 punto de vida.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'damagedOneWins',
    target: 3,
  },
  {
    id: 'p3-09',
    title: 'No necesito ni moverme',
    description: 'Destruye dos unidades con el lanzamisiles sin moverlo entre disparos.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'stationaryMissileKills',
    target: 2,
  },
  {
    id: 'p3-10',
    title: 'Morir matando',
    description: 'Gana 3 partidas destruyendo la fortaleza enemiga con un ataque kamikaze.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'kamikazeWins',
    target: 3,
  },
  {
    id: 'p3-11',
    title: '¿Dónde pongo los cadáveres?',
    description: 'Elimina 500 unidades rivales.',
    tier: 2,
    hidden: false,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 2,
    metric: 'kills',
    target: 500,
  },
  {
    id: 'p3-12',
    title: 'Pues tampoco era tan bueno',
    description:
      'Gana una partida contra un jugador con al menos 300 puntos de clasificación más que tú.',
    tier: 2,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'ratingGap',
    target: 300,
  },
  {
    id: 'p3-13',
    title: 'Veterano de guerra',
    description: 'Juega 30 partidas en línea.',
    tier: 2,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'matches',
    target: 30,
  },
  {
    id: 'p3-14',
    title: '¿Otra vez tú?',
    description: 'Juega 15 partidas contra Hexfortia.',
    tier: 2,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 2,
    metric: 'matches',
    target: 15,
  },
  {
    id: 'p3-15',
    title: 'Mañana también',
    description: 'Mantén una racha de actividad de 25 días.',
    tier: 2,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'activity',
    target: 25,
  },
  {
    id: 'p3-16',
    title: 'Se busca rival decente',
    description: 'Gana 15 partidas en línea.',
    tier: 2,
    hidden: true,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'wins',
    target: 15,
  },
  {
    id: 'p3-17',
    title: '¡Maldito traidor!',
    description: 'Utiliza una unidad capturada para atacar a su antiguo propietario.',
    tier: 2,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'capturedAttack',
    target: 1,
  },
  {
    id: 'p3-18',
    title: 'Póker de bajas',
    description: 'Destruye cinco unidades con un avión en una misma partida.',
    tier: 2,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'planeKills',
    target: 5,
  },
  {
    id: 'p3-19',
    title: 'Ni me despeiné',
    description: 'Gana una partida en línea conservando al menos el 50% de tus unidades iniciales.',
    tier: 2,
    hidden: true,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'halfSurvivors',
    target: 1,
  },
  {
    id: 'p3-20',
    title: 'Guerra relámpago',
    description: 'Gana una partida en menos de 40 turnos.',
    tier: 2,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 2,
    metric: 'quickWins',
    target: 1,
  },
  {
    id: 'p4-01',
    title: 'Ahora sí impones respeto',
    description: 'Alcanza 2000 puntos de clasificación.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'onlineRating',
    target: 2000,
  },
  {
    id: 'p4-02',
    title: 'De aquí a la leyenda',
    description: 'Alcanza el TOP 1000 en la clasificación histórica.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 0,
    metric: 'historicalRank',
    target: 1000,
  },
  {
    id: 'p4-03',
    title: '¿Quién quiere perder?',
    description: 'Gana 50 partidas en línea.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'wins',
    target: 50,
  },
  {
    id: 'p4-04',
    title: 'No era suerte',
    description: 'Gana 10 partidas consecutivas en línea.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'winStreak',
    target: 10,
  },
  {
    id: 'p4-05',
    title: 'Y aún me sobra tiempo',
    description:
      'Gana 25 partidas en línea con el tiempo total configurado a 5 minutos por jugador.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'blitzWins',
    target: 25,
  },
  {
    id: 'p4-06',
    title: 'No ha quedado ni el apuntador',
    description: 'Gana 25 partidas destruyendo todas las unidades enemigas.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'cleanWins',
    target: 25,
  },
  {
    id: 'p4-07',
    title: 'Último superviviente',
    description: 'Gana 10 partidas conservando únicamente una unidad, además de la fortaleza.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'lastSurvivorWins',
    target: 10,
  },
  {
    id: 'p4-08',
    title: 'No es nada personal',
    description: 'Gana 10 partidas después de que tu fortaleza haya perdido 1 punto de vida.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'damagedOneWins',
    target: 10,
  },
  {
    id: 'p4-09',
    title: 'Era parte del plan',
    description: 'Captura una unidad que posteriormente inflija el golpe final a la fortaleza.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'capturedFinish',
    target: 1,
  },
  {
    id: 'p4-10',
    title: 'De la chatarra a la gloria',
    description:
      'Después de utilizar los dos misiles del lanzamisiles, abandónalo para convertirlo en soldado y destruye la fortaleza enemiga con ese soldado.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'missileSoldierFinish',
    target: 1,
  },
  {
    id: 'p4-11',
    title: 'Que no falte nadie',
    description:
      'Utiliza los siete tipos de unidades para destruir al menos una unidad enemiga en una misma partida.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'allTypesKill',
    target: 1,
  },
  {
    id: 'p4-12',
    title: 'Dominio absoluto',
    description: 'Gana una partida en línea conservando al menos el 75% de tus unidades iniciales.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'threeQuarterSurvivors',
    target: 1,
  },
  {
    id: 'p4-13',
    title: '¿Quién recoge todo esto?',
    description: 'Elimina 1500 unidades rivales.',
    tier: 3,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'kills',
    target: 1500,
  },
  {
    id: 'p4-14',
    title: '¿Quién dijo imposible?',
    description:
      'Gana una partida contra un jugador con al menos 600 puntos de clasificación más que tú.',
    tier: 3,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'ratingGap',
    target: 600,
  },
  {
    id: 'p4-15',
    title: 'Ni un día de descanso',
    description: 'Mantén una racha de actividad de 50 días.',
    tier: 3,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'activity',
    target: 50,
  },
  {
    id: 'p4-16',
    title: 'Ya he perdido la cuenta',
    description: 'Juega 100 partidas en línea.',
    tier: 3,
    hidden: true,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'matches',
    target: 100,
  },
  {
    id: 'p4-17',
    title: 'Nos volvemos a ver',
    description: 'Juega 50 partidas contra Hexfortia.',
    tier: 3,
    hidden: true,
    modes: ['machine'],
    minDifficulty: 3,
    metric: 'matches',
    target: 50,
  },
  {
    id: 'p4-18',
    title: 'No hay distancia que se me resista',
    description:
      'Ataca con el embestidor a una unidad enemiga situada a al menos 10 casillas de distancia.',
    tier: 3,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'ramAttackDistance',
    target: 10,
  },
  {
    id: 'p4-19',
    title: 'No estaba muerto',
    description:
      'Gana una partida en línea después de que tu fortaleza haya perdido 2 puntos de vida.',
    tier: 3,
    hidden: true,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'damagedTwoWins',
    target: 1,
  },
  {
    id: 'p4-20',
    title: 'Ha llegado mi momento',
    description: 'Alcanza el TOP 100 en la clasificación mensual.',
    tier: 3,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 0,
    metric: 'monthlyRank',
    target: 100,
  },
  {
    id: 'p5-01',
    title: '¿Quién va a pararme?',
    description: 'Alcanza 3000 puntos de clasificación.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'onlineRating',
    target: 3000,
  },
  {
    id: 'p5-02',
    title: 'El terror de las máquinas',
    description: 'Alcanza el TOP 100 en la clasificación histórica contra Hexfortia.',
    tier: 4,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 0,
    metric: 'historicalRank',
    target: 100,
  },
  {
    id: 'p5-03',
    title: 'El terror de la humanidad',
    description: 'Alcanza el TOP 100 en la clasificación histórica en línea.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'historicalRank',
    target: 100,
  },
  {
    id: 'p5-04',
    title: 'Nací para hacer historia',
    description: 'Alcanza el TOP 10 en la clasificación mensual.',
    tier: 4,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 0,
    metric: 'monthlyRank',
    target: 10,
  },
  {
    id: 'p5-05',
    title: '¿Has probado a reiniciarte?',
    description: 'Gana 100 partidas contra Hexfortia.',
    tier: 4,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 3,
    metric: 'wins',
    target: 100,
  },
  {
    id: 'p5-06',
    title: 'Esto ya es una profesión',
    description: 'Gana 250 partidas en línea.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'wins',
    target: 250,
  },
  {
    id: 'p5-07',
    title: 'Ya puedes dejar de intentarlo',
    description: 'Gana 25 partidas consecutivas en línea.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'winStreak',
    target: 25,
  },
  {
    id: 'p5-08',
    title: 'Con prisa, pero sin pausa',
    description:
      'Gana 100 partidas en línea con el tiempo total configurado a 5 minutos por jugador.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'blitzWins',
    target: 100,
  },
  {
    id: 'p5-09',
    title: 'Ni un rasguño',
    description: 'Gana una partida destruyendo la fortaleza enemiga sin perder ninguna unidad.',
    tier: 4,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'noLossWin',
    target: 1,
  },
  {
    id: 'p5-10',
    title: 'Tú sí que vales',
    description: 'Gana 25 partidas conservando únicamente una unidad, además de la fortaleza.',
    tier: 4,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'lastSurvivorWins',
    target: 25,
  },
  {
    id: 'p5-11',
    title: 'Yo no me doy por vencido',
    description: 'Gana 15 partidas después de que tu fortaleza haya perdido 2 puntos de vida.',
    tier: 4,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'damagedTwoWins',
    target: 15,
  },
  {
    id: 'p5-12',
    title: 'Don’t stop me now',
    description: 'Elimina 3000 unidades rivales.',
    tier: 4,
    hidden: false,
    modes: ['machine', 'online'],
    minDifficulty: 3,
    metric: 'kills',
    target: 3000,
  },
  {
    id: 'p5-13',
    title: 'Ya somos familia',
    description: 'Juega 250 partidas contra Hexfortia.',
    tier: 4,
    hidden: false,
    modes: ['machine'],
    minDifficulty: 3,
    metric: 'matches',
    target: 250,
  },
  {
    id: 'p5-14',
    title: 'Veterano de guerra',
    description: 'Juega 500 partidas en línea.',
    tier: 4,
    hidden: false,
    modes: ['online'],
    minDifficulty: 0,
    metric: 'matches',
    target: 500,
  },
  {
    id: 'p5-15',
    title: 'Año sabático',
    description: 'Mantén una racha de actividad de 365 días.',
    tier: 4,
    hidden: false,
    modes: [],
    minDifficulty: 0,
    metric: 'activity',
    target: 365,
  },
  {
    id: 'p5-16',
    title: 'Si ya saben cómo me pongo, ¿pa’ qué me invitan?',
    description: 'Juega 1000 partidas.',
    tier: 4,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'matches',
    target: 1000,
  },
  {
    id: 'p5-17',
    title: 'Se me ha ido de las manos',
    description: 'Elimina 10000 unidades rivales.',
    tier: 4,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 0,
    metric: 'kills',
    target: 10000,
  },
  {
    id: 'p5-18',
    title: '¿Y ahora qué hago con mi vida?',
    description: 'Alcanza el nivel 100.',
    tier: 4,
    hidden: true,
    modes: [],
    minDifficulty: 0,
    metric: 'level',
    target: 100,
  },
  {
    id: 'p5-19',
    title: 'Leyenda viviente',
    description: 'Alcanza el TOP 10 en la clasificación histórica.',
    tier: 4,
    hidden: true,
    modes: ['machine', 'online'],
    minDifficulty: 0,
    metric: 'historicalRank',
    target: 10,
  },
  {
    id: 'p5-20',
    title: 'Que empiece la batalla',
    description: 'Juega una partida en el año 2488.',
    tier: 4,
    hidden: true,
    modes: ['machine', 'online', 'local'],
    minDifficulty: 0,
    metric: 'year2488',
    target: 1,
  },
] as const;
